<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MahK6ub' shared service.

return $this->privates['.service_locator.MahK6ub'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('don' => function (): \App\Entity\Don {
    return ($this->privates['.errored..service_locator.MahK6ub.App\Entity\Don'] ?? $this->load('getDonService.php'));
}));
