<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NSpv_ue' shared service.

return $this->privates['.service_locator.NSpv_ue'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('mailer' => function () {
    return ($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php'));
}, 'projetchoice' => function (): \App\Repository\ProjetRepository {
    return ($this->privates['App\Repository\ProjetRepository'] ?? $this->load('getProjetRepositoryService.php'));
}));
