<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.MahK6ub.App\Entity\Don' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.MahK6ub": it references class "App\\Entity\\Don" but no such service exists.');
