<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v6lzbUy' shared service.

return $this->privates['.service_locator.v6lzbUy'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('donRepository' => function (): \App\Repository\DonRepository {
    return ($this->privates['App\Repository\DonRepository'] ?? $this->load('getDonRepositoryService.php'));
}));
