<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\DashboardController::allDon' => function () {
    return ($this->privates['.service_locator.v6lzbUy'] ?? $this->load('get_ServiceLocator_V6lzbUyService.php'));
}, 'App\\Controller\\DashboardController::allProjet' => function () {
    return ($this->privates['.service_locator.M1qkeEv'] ?? $this->load('get_ServiceLocator_M1qkeEvService.php'));
}, 'App\\Controller\\DashboardController::delete' => function () {
    return ($this->privates['.service_locator.M1qkeEv'] ?? $this->load('get_ServiceLocator_M1qkeEvService.php'));
}, 'App\\Controller\\DashboardController::edit' => function () {
    return ($this->privates['.service_locator.BgZPdw3'] ?? $this->load('get_ServiceLocator_BgZPdw3Service.php'));
}, 'App\\Controller\\DashboardController::index' => function () {
    return ($this->privates['.service_locator.pDN53fn'] ?? $this->load('get_ServiceLocator_PDN53fnService.php'));
}, 'App\\Controller\\DonController::delete' => function () {
    return ($this->privates['.service_locator.MahK6ub'] ?? $this->load('get_ServiceLocator_MahK6ubService.php'));
}, 'App\\Controller\\DonController::edit' => function () {
    return ($this->privates['.service_locator.MahK6ub'] ?? $this->load('get_ServiceLocator_MahK6ubService.php'));
}, 'App\\Controller\\DonController::index' => function () {
    return ($this->privates['.service_locator.v6lzbUy'] ?? $this->load('get_ServiceLocator_V6lzbUyService.php'));
}, 'App\\Controller\\DonController::show' => function () {
    return ($this->privates['.service_locator.MahK6ub'] ?? $this->load('get_ServiceLocator_MahK6ubService.php'));
}, 'App\\Controller\\FrontController::SaveProjet' => function () {
    return ($this->privates['.service_locator.GA79Oox'] ?? $this->load('get_ServiceLocator_GA79OoxService.php'));
}, 'App\\Controller\\FrontController::edit' => function () {
    return ($this->privates['.service_locator.BgZPdw3'] ?? $this->load('get_ServiceLocator_BgZPdw3Service.php'));
}, 'App\\Controller\\FrontController::faireDon' => function () {
    return ($this->privates['.service_locator.tn_dlMk'] ?? $this->load('get_ServiceLocator_TnDlMkService.php'));
}, 'App\\Controller\\FrontController::findID' => function () {
    return ($this->privates['.service_locator.7oaGzLz'] ?? $this->load('get_ServiceLocator_7oaGzLzService.php'));
}, 'App\\Controller\\FrontController::findallProjet' => function () {
    return ($this->privates['.service_locator.pasxs_k'] ?? $this->load('get_ServiceLocator_PasxsKService.php'));
}, 'App\\Controller\\FrontController::index' => function () {
    return ($this->privates['.service_locator.bFBp6Ie'] ?? $this->load('get_ServiceLocator_BFBp6IeService.php'));
}, 'App\\Controller\\FrontController::mescampagne' => function () {
    return ($this->privates['.service_locator.GA79Oox'] ?? $this->load('get_ServiceLocator_GA79OoxService.php'));
}, 'App\\Controller\\RegistrationController::register' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\UserController::delete' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}, 'App\\Controller\\UserController::edit' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}, 'App\\Controller\\UserController::index' => function () {
    return ($this->privates['.service_locator.pDN53fn'] ?? $this->load('get_ServiceLocator_PDN53fnService.php'));
}, 'App\\Controller\\UserController::show' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}, 'App\\Controller\\DashboardController:allDon' => function () {
    return ($this->privates['.service_locator.v6lzbUy'] ?? $this->load('get_ServiceLocator_V6lzbUyService.php'));
}, 'App\\Controller\\DashboardController:allProjet' => function () {
    return ($this->privates['.service_locator.M1qkeEv'] ?? $this->load('get_ServiceLocator_M1qkeEvService.php'));
}, 'App\\Controller\\DashboardController:delete' => function () {
    return ($this->privates['.service_locator.M1qkeEv'] ?? $this->load('get_ServiceLocator_M1qkeEvService.php'));
}, 'App\\Controller\\DashboardController:edit' => function () {
    return ($this->privates['.service_locator.BgZPdw3'] ?? $this->load('get_ServiceLocator_BgZPdw3Service.php'));
}, 'App\\Controller\\DashboardController:index' => function () {
    return ($this->privates['.service_locator.pDN53fn'] ?? $this->load('get_ServiceLocator_PDN53fnService.php'));
}, 'App\\Controller\\DonController:delete' => function () {
    return ($this->privates['.service_locator.MahK6ub'] ?? $this->load('get_ServiceLocator_MahK6ubService.php'));
}, 'App\\Controller\\DonController:edit' => function () {
    return ($this->privates['.service_locator.MahK6ub'] ?? $this->load('get_ServiceLocator_MahK6ubService.php'));
}, 'App\\Controller\\DonController:index' => function () {
    return ($this->privates['.service_locator.v6lzbUy'] ?? $this->load('get_ServiceLocator_V6lzbUyService.php'));
}, 'App\\Controller\\DonController:show' => function () {
    return ($this->privates['.service_locator.MahK6ub'] ?? $this->load('get_ServiceLocator_MahK6ubService.php'));
}, 'App\\Controller\\FrontController:SaveProjet' => function () {
    return ($this->privates['.service_locator.GA79Oox'] ?? $this->load('get_ServiceLocator_GA79OoxService.php'));
}, 'App\\Controller\\FrontController:edit' => function () {
    return ($this->privates['.service_locator.BgZPdw3'] ?? $this->load('get_ServiceLocator_BgZPdw3Service.php'));
}, 'App\\Controller\\FrontController:faireDon' => function () {
    return ($this->privates['.service_locator.tn_dlMk'] ?? $this->load('get_ServiceLocator_TnDlMkService.php'));
}, 'App\\Controller\\FrontController:findID' => function () {
    return ($this->privates['.service_locator.7oaGzLz'] ?? $this->load('get_ServiceLocator_7oaGzLzService.php'));
}, 'App\\Controller\\FrontController:findallProjet' => function () {
    return ($this->privates['.service_locator.pasxs_k'] ?? $this->load('get_ServiceLocator_PasxsKService.php'));
}, 'App\\Controller\\FrontController:index' => function () {
    return ($this->privates['.service_locator.bFBp6Ie'] ?? $this->load('get_ServiceLocator_BFBp6IeService.php'));
}, 'App\\Controller\\FrontController:mescampagne' => function () {
    return ($this->privates['.service_locator.GA79Oox'] ?? $this->load('get_ServiceLocator_GA79OoxService.php'));
}, 'App\\Controller\\RegistrationController:register' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\UserController:delete' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}, 'App\\Controller\\UserController:edit' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}, 'App\\Controller\\UserController:index' => function () {
    return ($this->privates['.service_locator.pDN53fn'] ?? $this->load('get_ServiceLocator_PDN53fnService.php'));
}, 'App\\Controller\\UserController:show' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
