<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pasxs_k' shared service.

return $this->privates['.service_locator.pasxs_k'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('donRepo' => function (): \App\Repository\DonRepository {
    return ($this->privates['App\Repository\DonRepository'] ?? $this->load('getDonRepositoryService.php'));
}, 'listprojets' => function (): \App\Repository\ProjetRepository {
    return ($this->privates['App\Repository\ProjetRepository'] ?? $this->load('getProjetRepositoryService.php'));
}));
