<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tn_dlMk' shared service.

return $this->privates['.service_locator.tn_dlMk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('projetchoice' => function (): \App\Repository\ProjetRepository {
    return ($this->privates['App\Repository\ProjetRepository'] ?? $this->load('getProjetRepositoryService.php'));
}));
