<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container60r1ITZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container60r1ITZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container60r1ITZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container60r1ITZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container60r1ITZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => '60r1ITZ',
    'container.build_id' => '2a0d2ef8',
    'container.build_time' => 1548530758,
), __DIR__.\DIRECTORY_SEPARATOR.'Container60r1ITZ');
