<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZBV51a\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZBV51a/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMZBV51a.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMZBV51a\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMZBV51a\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MZBV51a',
    'container.build_id' => '92b7225c',
    'container.build_time' => 1548757475,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZBV51a');
